### ISSUE TITLE
拉取最新项目文件，报错不能运行。

### ISSUE THREAD

**Issue by aron0524** [viarotel-org/vite-uniapp-template#13]
npm run dev:h5

Error: Failed to import ESLint, do you install or configure eslintPath?
    at formatError (file:///C:/Users/Administrator/Desktop/vite-uniapp-template/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41418:46)
    at Context.error (file:///C:/Users/Administrator/Desktop/vite-uniapp-template/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41414:19)
    at Context.buildStart (C:\Users\Administrator\Desktop\vite-uniapp-template\node_modules\vite-plugin-eslint\dist\index.js:1:1778)
    at async Promise.all (index 6)
    at async hookParallel (file:///C:/Users/Administrator/Desktop/vite-uniapp-template/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41304:9)
    at async Object.buildStart (file:///C:/Users/Administrator/Desktop/vite-uniapp-template/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41589:13)        
    at async file:///C:/Users/Administrator/Desktop/vite-uniapp-template/node_modules/vite/dist/node/chunks/dep-ca21228b.js:61392:13
    at async Server.httpServer.listen (file:///C:/Users/Administrator/Desktop/vite-uniapp-template/node_modules/vite/dist/node/chunks/dep-ca21228b.js:61407:17)

**Comment by viarotel** [comment]
使用的什么包管理器和代码编辑器，node版本号是多少

**Comment by aron0524** [comment]
node -v
v16.14.2
npm -v 
9.3.1
yarn -v
1.22.19

**Comment by viarotel** [comment]
> node -v v16.14.2 npm -v 9.3.1 yarn -v 1.22.19

好的我这边找时间测试一下

**Comment by viarotel** [comment]
> node -v v16.14.2 npm -v 9.3.1 yarn -v 1.22.19

v2.2.1 已解决该问题 请拉取项目后删除 node_modules yarn.lock/package-lock.json 后重新安装以来后重试

**Comment by viarotel** [comment]
> > node -v v16.14.2 npm -v 9.3.1 yarn -v 1.22.19
> 
> v2.2.1 已解决该问题 请拉取项目后删除 node_modules yarn.lock/package-lock.json 后重新安装依赖后重试

**Comment by viarotel** [comment]
> > > node -v v16.14.2 npm -v 9.3.1 yarn -v 1.22.19
> > 
> > 
> > v2.2.1 已解决该问题 请拉取项目后删除 node_modules yarn.lock/package-lock.json 后重新安装依赖重试

**Comment by viarotel** [comment]
> npm run dev:h5
> 
> Error: Failed to import ESLint, do you install or configure eslintPath? at formatError (file:///C:/Users/Administrator/Desktop/vite-uniapp-template/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41418:46) at Context.error (file:///C:/Users/Administrator/Desktop/vite-uniapp-template/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41414:19) at Context.buildStart (C:\Users\Administrator\Desktop\vite-uniapp-template\node_modules\vite-plugin-eslint\dist\index.js:1:1778) at async Promise.all (index 6) at async hookParallel (file:///C:/Users/Administrator/Desktop/vite-uniapp-template/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41304:9) at async Object.buildStart (file:///C:/Users/Administrator/Desktop/vite-uniapp-template/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41589:13) at async file:///C:/Users/Administrator/Desktop/vite-uniapp-template/node_modules/vite/dist/node/chunks/dep-ca21228b.js:61392:13 at async Server.httpServer.listen (file:///C:/Users/Administrator/Desktop/vite-uniapp-template/node_modules/vite/dist/node/chunks/dep-ca21228b.js:61407:17)

v2.2.1 已解决该问题 请拉取项目后删除 node_modules yarn.lock/package-lock.json 后重新安装依赖重试
